const path = require("path");
const cheerio = require("cheerio");
const fs = require("fs-extra");
const { detectComponents } = require("./component-detector");
const { slugify } = require("./utils");

const BUILD_RULES = {
  header: ["header", '[role="banner"]', '[class*="site-header"], [id*="header"]'],
  navbar: ["nav", '[role="navigation"]', '[class*="navbar"], [class*="main-menu"]'],
  hero: ['[class~="hero"], [id~="hero"]', '[class*="hero-"], [class*="-hero"], [class*="jumbotron"]', '[class*="banner"]'],
  cards: ['[class~="card"], [class*="-card"], [class*="card-"]', "main article"],
  gallery: ['[class*="gallery"], [id*="gallery"]', '[data-gallery], [class*="lightbox"]'],
  faq: ['[class*="faq"], [id*="faq"]', "details", '[itemtype*="FAQPage"]'],
  "contact-form": ['form[action*="contact"], form[class*="contact"]', "form textarea", "form input[type='email']"],
  "product-grid": ['[class*="product-grid"], [class*="products-grid"]', ".woocommerce ul.products, .products .product", '[class*="product-card"]'],
  pricing: ['[class*="pricing"], [id*="pricing"]', '[class*="price-card"], [class*="plan-card"]'],
  testimonials: ['[class*="testimonial"], [id*="testimonial"]', '[class*="review-card"], blockquote[cite]'],
  "blog-cards": ['[class*="post-card"], [class*="blog-card"]', 'article[class*="post"], [class*="blog-grid"] article'],
  sidebar: ['aside, [role="complementary"]', '[class~="sidebar"], [id*="sidebar"]'],
  breadcrumb: ['nav[aria-label*="breadcrumb" i], [class*="breadcrumb"]', '[itemtype*="BreadcrumbList"]'],
  modal: ['[class*="modal"], [role="dialog"]', '[data-modal], [aria-modal="true"]'],
  accordion: ['details', '[class*="accordion"], [data-accordion]'],
  tabs: ['[role="tablist"], [role="tab"]', '[class*="tabs"], [data-tabs]'],
  footer: ["footer", '[role="contentinfo"]', '[class*="site-footer"], [id*="footer"]'],
};

const OUTPUT_COMPONENT_DIR = {
  "static-html": "components",
  php: "components",
  laravel: path.join("resources", "views", "components"),
  nextjs: "components",
  react: path.join("src", "components"),
  vue: path.join("src", "components"),
  wordpress: "template-parts",
  aspnet: path.join("Views", "Shared", "Components"),
  express: "components",
  node: "components",
};

function pickSelector($, selectors) {
  for (const selector of selectors) {
    try {
      const found = $(selector).first();
      if (found.length) return found;
    } catch {
      // Ignore selector support differences.
    }
  }
  return null;
}

function wrapStaticComponent(name, html) {
  return `<!-- ${name} component start -->\n${html}\n<!-- ${name} component end -->\n`;
}

function wrapPhpComponent(name, html) {
  return `<?php\n// ${name} component generated by Website Rebuilder AI Pro.\n?>\n${html}\n`;
}

function wrapJsxComponent(name, html) {
  const markup = JSON.stringify(html).replace(/</g, "\\u003c");
  return `const markup = ${markup};\n\nexport default function ${name}() {\n  return <section data-component="${name}" dangerouslySetInnerHTML={{ __html: markup }} />;\n}\n`;
}

function wrapVueComponent(html) {
  return `<template>\n${html}\n</template>\n`;
}

function componentFileInfo(outputType, name) {
  const folder = OUTPUT_COMPONENT_DIR[outputType] || "components";
  const safeName = slugify(name, "component");
  const ext =
    outputType === "php" ||
    outputType === "laravel" ||
    outputType === "wordpress" ||
    outputType === "aspnet"
      ? "php"
      : outputType === "vue"
        ? "vue"
        : "jsx";
  if (outputType === "static-html") return { file: path.join(folder, `${safeName}.html`) };
  if (outputType === "php") return { file: path.join(folder, `${safeName}.php`) };
  if (outputType === "laravel") return { file: path.join(folder, `${safeName}.blade.php`) };
  if (outputType === "vue") return { file: path.join(folder, `${safeName}.vue`) };
  if (outputType === "wordpress") return { file: path.join(folder, `${safeName}.php`) };
  if (outputType === "aspnet") return { file: path.join(folder, `${safeName}.cshtml`) };
  return { file: path.join(folder, `${safeName}.${ext}`) };
}

function buildComponentsFromAnalysis(html, detectedComponents = [], $ = cheerio.load(html, { decodeEntities: false })) {
  const fallback = detectedComponents.length ? detectedComponents : detectComponents(html);
  const used = new Set();
  return fallback.map((component) => {
    const selectors = BUILD_RULES[component.type] || [];
    const element = pickSelector($, selectors) || pickSelector($, [component.type, component.name]);
    const markup = element ? $.html(element) : html;
    let name = component.name || component.type || "Component";
    let suffix = 2;
    while (used.has(name)) name = `${component.name || component.type || "Component"}${suffix++}`;
    used.add(name);
    const fileInfo = componentFileInfo("static-html", name);
    return {
      name,
      type: component.type || slugify(name),
      confidence: component.confidence || 70,
      html: markup,
      selector: selectors[0] || null,
      file: fileInfo.file,
    };
  });
}

function addSectionComments(html, components = []) {
  const $ = cheerio.load(html, { decodeEntities: false });
  for (const component of components) {
    const selectors = BUILD_RULES[component.type] || [];
    const element = pickSelector($, selectors);
    if (element && element.length) {
      element.before(`\n<!-- ${component.name} component -->\n`);
      element.after(`\n<!-- End ${component.name} -->\n`);
    }
  }
  return $.html();
}

async function writeComponentFile(directory, component, outputType) {
  const info = componentFileInfo(outputType, component.name);
  const fullPath = path.join(directory, info.file);
  await fs.outputFile(
    fullPath,
    outputType === "static-html"
      ? wrapStaticComponent(component.name, component.html)
      : outputType === "php"
        ? wrapPhpComponent(component.name, component.html)
        : outputType === "vue"
          ? wrapVueComponent(component.html)
          : outputType === "laravel" || outputType === "wordpress" || outputType === "aspnet"
            ? component.html
            : wrapJsxComponent(component.name, component.html),
  );
  return info.file;
}

async function writePhpIncludes(directory, html) {
  const $ = cheerio.load(html, { decodeEntities: false });
  const headerMarkup = $("header").first().toString() || "";
  const footerMarkup = $("footer").first().toString() || "";
  const headMarkup = $("head").html() || "";
  await fs.outputFile(
    path.join(directory, "includes", "header.php"),
    `<!doctype html><html lang="en"><head>${headMarkup}</head><body>${headerMarkup}\n`,
  );
  await fs.outputFile(
    path.join(directory, "includes", "footer.php"),
    `${footerMarkup}\n</body></html>\n`,
  );
}

async function buildComponentFiles({
  html,
  outputType,
  directory,
  enabled = true,
  detectedComponents = [],
  projectName = "Website",
  mode = "mirror",
}) {
  if (!enabled) {
    return { components: [], componentMap: [], generatedFiles: [] };
  }

  const $ = cheerio.load(html, { decodeEntities: false });
  const components = buildComponentsFromAnalysis(html, detectedComponents, $);
  const generatedFiles = [];

  for (const component of components) {
    const file = await writeComponentFile(directory, component, outputType);
    component.file = file;
    generatedFiles.push(file);
  }

  if (outputType === "php") {
    await writePhpIncludes(directory, html);
    generatedFiles.push("includes/header.php", "includes/footer.php");
  }

  if (["nextjs", "react", "vue"].includes(outputType) && mode !== "mirror") {
    generatedFiles.push(
      outputType === "vue" ? path.join("src", "views", "Home.vue") : path.join("src", "pages", "Home.jsx"),
    );
  }

  // Future OpenAI integration point:
  // detected component markup and confidence data can be sent to a model here
  // to generate framework-native component code after schema validation.

  return {
    components,
    componentMap: components.map((component) => ({
      name: component.name,
      type: component.type,
      confidence: component.confidence,
      file: component.file,
    })),
    generatedFiles,
  };
}

module.exports = {
  addSectionComments,
  buildComponentFiles,
  buildComponentsFromAnalysis,
  extractBuildableComponents: buildComponentsFromAnalysis,
};
