const path = require("path");
const fs = require("fs-extra");

async function writeExportPreset(directory, exportFormat, projectName, outputType = "static-html") {
  const format = String(exportFormat || "zip").toLowerCase();
  if (format === "zip") return;

  const docs = [];

  if (format === "git") {
    await fs.writeFile(
      path.join(directory, ".gitignore"),
      "node_modules/\n.DS_Store\nThumbs.db\n.env\noutput/\n",
    );
    docs.push(
      "Git export preset: this package includes a basic .gitignore so the scaffold can be committed directly.",
    );
  }

  if (format === "docker") {
    const dockerfile =
      outputType === "static-html"
        ? "FROM nginx:alpine\nCOPY . /usr/share/nginx/html\n"
        : outputType === "php" || outputType === "wordpress"
          ? "FROM php:8.3-apache\nCOPY . /var/www/html/\nRUN a2enmod rewrite\n"
          : outputType === "aspnet"
            ? "FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build\nWORKDIR /src\nCOPY . .\n"
            : "FROM node:20-alpine\nWORKDIR /app\nCOPY . .\nRUN npm install || true\nEXPOSE 3000\nCMD [\"node\", \"server.js\"]\n";
    await fs.writeFile(path.join(directory, "Dockerfile"), dockerfile);
    await fs.writeFile(
      path.join(directory, "docker-compose.yml"),
      "services:\n  app:\n    build: .\n    ports:\n      - \"3000:3000\"\n",
    );
    await fs.writeFile(
      path.join(directory, ".dockerignore"),
      "node_modules\noutput\n.git\n",
    );
    docs.push(
      "Docker export preset: a lightweight Dockerfile and compose file are included for quick containerization.",
    );
  }

  if (format === "plesk" || format === "cpanel") {
    docs.push(
      `${format === "plesk" ? "Plesk" : "cPanel"} export preset: the archive is ready for upload and already includes the Apache support files generated by the engine.`,
    );
  }

  if (format === "ftp") {
    await fs.writeFile(
      path.join(directory, "FTP-INSTRUCTIONS.txt"),
      `Upload the contents of ${projectName} to your hosting root using FTP.\nKeep the folder structure unchanged.\n`,
    );
    docs.push(
      "FTP export preset: upload the project contents directly to the hosting root.",
    );
  }

  if (docs.length) {
    const existing = (await fs.readFile(path.join(directory, "README.md"), "utf8")).trim();
    await fs.writeFile(
      path.join(directory, "README.md"),
      `${existing}\n\n## Export preset\n\n${docs.map((line) => `- ${line}`).join("\n")}\n`,
    );
  }
}

module.exports = { writeExportPreset };
