function classifyMessage(message = "") {
  const text = String(message).toLowerCase();
  if (/(remove|delete).*(css|style)/.test(text)) return "remove-css";
  if (/(extract|inline).*(css|style)/.test(text)) return "extract-css";
  if (/(extract|inline).*(js|javascript)/.test(text)) return "extract-js";
  if (/(semantic|header|nav|footer|main)/.test(text)) return "semantic-html";
  if (/(alt|image)/.test(text)) return "alt-tags";
  if (/(meta|seo|title|description)/.test(text)) return "seo-tags";
  if (/(robot|sitemap|htaccess|docker)/.test(text)) return "support-files";
  return "general";
}

function buildChatResponse({ message, project }) {
  const action = classifyMessage(message);
  const base = {
    projectId: project?.id || null,
    action,
    message: String(message || ""),
  };

  const responses = {
    "remove-css":
      "Rule-based cleanup queued: duplicate CSS blocks will be reduced in the next rebuild. A future AI provider can replace this heuristic.",
    "extract-css":
      "Rule-based cleanup queued: inline CSS will be extracted into project styles during rebuild. Future AI integration can produce richer refactors.",
    "extract-js":
      "Rule-based cleanup queued: inline JavaScript will be extracted into script files during rebuild.",
    "semantic-html":
      "Rule-based cleanup queued: semantic HTML pass will favor header, nav, main, section, article, and footer structure.",
    "alt-tags":
      "Rule-based cleanup queued: image alt attributes will be inferred where possible during rebuild.",
    "seo-tags":
      "Rule-based cleanup queued: meta title, description, and canonical hints will be strengthened.",
    "support-files":
      "Rule-based cleanup queued: robots.txt, sitemap.xml, .htaccess, and Dockerfile support files can be generated by the rebuild/export pipeline.",
    general:
      "Rule-based chat is active. Future provider integration hooks are present, but this build currently uses deterministic actions only.",
  };

  return { ...base, reply: responses[action], provider: "rule-based" };
}

module.exports = { classifyMessage, buildChatResponse };
