const path = require("path");
const fs = require("fs-extra");

async function generateNextJs({
  html,
  stagingDirectory,
  projectName,
  sourceUrl,
}) {
  const siteDirectory = path.join(stagingDirectory, "public", "site");
  await fs.ensureDir(siteDirectory);

  const sourceAssets = path.join(stagingDirectory, "assets");
  const targetAssets = path.join(siteDirectory, "assets");
  if (await fs.pathExists(sourceAssets)) {
    await fs.move(sourceAssets, targetAssets, { overwrite: true });
  }
  await fs.writeFile(path.join(siteDirectory, "index.html"), html);

  await fs.outputFile(
    path.join(stagingDirectory, "app", "layout.js"),
    `import "./globals.css";

export const metadata = {
  title: "Rebuilt Website",
  description: "Generated by Website Rebuilder AI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
  );

  await fs.outputFile(
    path.join(stagingDirectory, "app", "page.js"),
    `export default function Home() {
  return (
    <main>
      <iframe
        src="/site/index.html"
        title="Rebuilt website"
        className="site-frame"
      />
    </main>
  );
}
`,
  );

  await fs.outputFile(
    path.join(stagingDirectory, "app", "globals.css"),
    `* { box-sizing: border-box; }
html, body, main { width: 100%; height: 100%; margin: 0; }
.site-frame { display: block; width: 100%; height: 100%; border: 0; }
`,
  );

  await fs.writeJson(
    path.join(stagingDirectory, "package.json"),
    {
      name: projectName.toLowerCase().replace(/[^a-z0-9-]+/g, "-"),
      version: "1.0.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: "^15.1.3",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
      },
    },
    { spaces: 2 },
  );

  await fs.writeFile(
    path.join(stagingDirectory, "README.md"),
    `# ${projectName}\n\nNext.js wrapper rebuilt from ${sourceUrl}.\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nThen open http://localhost:3000.\n`,
  );
}

module.exports = generateNextJs;
