const path = require("path");
const fs = require("fs-extra");

async function moveAssets(stagingDirectory, publicDirectory) {
  const source = path.join(stagingDirectory, "assets");
  if (await fs.pathExists(source)) {
    await fs.move(source, path.join(publicDirectory, "assets"), {
      overwrite: true,
    });
  }
}

async function generateLaravel({ html, stagingDirectory, projectName }) {
  const publicDirectory = path.join(stagingDirectory, "public");
  await fs.ensureDir(publicDirectory);
  await moveAssets(stagingDirectory, publicDirectory);
  await fs.writeFile(path.join(publicDirectory, "index.php"), html);
  await fs.outputFile(
    path.join(stagingDirectory, "routes", "web.php"),
    "<?php\n\nuse Illuminate\\Support\\Facades\\Route;\n\nRoute::view('/', 'welcome');\n",
  );
  await fs.outputFile(
    path.join(stagingDirectory, "resources", "views", "welcome.blade.php"),
    html,
  );
  await fs.writeJson(
    path.join(stagingDirectory, "composer.json"),
    {
      name: `generated/${projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
      description: "Laravel scaffold generated by Website Rebuilder AI Pro",
      require: { php: "^8.2", "laravel/framework": "^11.0" },
    },
    { spaces: 2 },
  );
  await fs.writeFile(
    path.join(stagingDirectory, "README.md"),
    `# ${projectName}\n\nBasic Laravel-compatible scaffold. Install Laravel dependencies before extending the generated placeholder.\n`,
  );
}

async function generateWordPress({ html, stagingDirectory, projectName }) {
  await fs.writeFile(
    path.join(stagingDirectory, "style.css"),
    `/*\nTheme Name: ${projectName}\nDescription: Generated by Website Rebuilder AI Pro\nVersion: 1.0.0\n*/\n`,
  );
  await fs.writeFile(path.join(stagingDirectory, "index.php"), html);
  await fs.writeFile(
    path.join(stagingDirectory, "functions.php"),
    "<?php\n\nfunction rebuilt_theme_assets() {\n    wp_enqueue_style('rebuilt-style', get_stylesheet_uri());\n}\nadd_action('wp_enqueue_scripts', 'rebuilt_theme_assets');\n",
  );
  await fs.writeFile(
    path.join(stagingDirectory, "README.md"),
    `# ${projectName}\n\nCopy this folder into \`wp-content/themes\`, then activate the theme in WordPress.\n`,
  );
}

async function generateReact({ html, stagingDirectory, projectName }) {
  const publicDirectory = path.join(stagingDirectory, "public");
  await fs.ensureDir(publicDirectory);
  await moveAssets(stagingDirectory, publicDirectory);
  await fs.writeFile(path.join(publicDirectory, "source.html"), html);
  await fs.outputFile(
    path.join(stagingDirectory, "src", "App.jsx"),
    `import "./index.css";

export default function App() {
  return <iframe className="site-frame" src="/source.html" title="Rebuilt website" />;
}
`,
  );
  await fs.outputFile(
    path.join(stagingDirectory, "src", "main.jsx"),
    `import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";

createRoot(document.getElementById("root")).render(<App />);
`,
  );
  await fs.outputFile(
    path.join(stagingDirectory, "src", "index.css"),
    "html, body, #root { height: 100%; margin: 0; } .site-frame { width: 100%; height: 100%; border: 0; }\n",
  );
  await fs.writeFile(
    path.join(stagingDirectory, "index.html"),
    '<!doctype html><html><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>',
  );
  await fs.writeJson(
    path.join(stagingDirectory, "package.json"),
    {
      name: projectName.toLowerCase().replace(/[^a-z0-9-]+/g, "-"),
      private: true,
      version: "1.0.0",
      type: "module",
      scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
      dependencies: { "@vitejs/plugin-react": "^4.3.4", vite: "^6.0.5", react: "^19.0.0", "react-dom": "^19.0.0" },
      devDependencies: {},
    },
    { spaces: 2 },
  );
  await fs.writeFile(
    path.join(stagingDirectory, "README.md"),
    `# ${projectName}\n\nBasic React/Vite scaffold. Run \`npm install\` and \`npm run dev\`.\n`,
  );
}

async function generateVue({ html, stagingDirectory, projectName }) {
  const publicDirectory = path.join(stagingDirectory, "public");
  await fs.ensureDir(publicDirectory);
  await moveAssets(stagingDirectory, publicDirectory);
  await fs.writeFile(path.join(publicDirectory, "source.html"), html);
  await fs.outputFile(
    path.join(stagingDirectory, "src", "App.vue"),
    `<template><iframe class="site-frame" src="/source.html" title="Rebuilt website" /></template>
<style>html, body, #app { height: 100%; margin: 0; } .site-frame { width: 100%; height: 100%; border: 0; }</style>
`,
  );
  await fs.outputFile(
    path.join(stagingDirectory, "src", "main.js"),
    'import { createApp } from "vue";\nimport App from "./App.vue";\ncreateApp(App).mount("#app");\n',
  );
  await fs.writeFile(
    path.join(stagingDirectory, "index.html"),
    '<!doctype html><html><body><div id="app"></div><script type="module" src="/src/main.js"></script></body></html>',
  );
  await fs.writeJson(
    path.join(stagingDirectory, "package.json"),
    {
      name: projectName.toLowerCase().replace(/[^a-z0-9-]+/g, "-"),
      private: true,
      version: "1.0.0",
      type: "module",
      scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
      dependencies: { "@vitejs/plugin-vue": "^5.2.1", vite: "^6.0.5", vue: "^3.5.13" },
      devDependencies: {},
    },
    { spaces: 2 },
  );
  await fs.writeFile(
    path.join(stagingDirectory, "README.md"),
    `# ${projectName}\n\nBasic Vue/Vite scaffold. Run \`npm install\` and \`npm run dev\`.\n`,
  );
}

async function generateAspNet({ html, stagingDirectory, projectName }) {
  const webRoot = path.join(stagingDirectory, "wwwroot");
  await fs.ensureDir(webRoot);
  await moveAssets(stagingDirectory, webRoot);
  await fs.writeFile(path.join(webRoot, "index.html"), html);
  await fs.writeFile(
    path.join(stagingDirectory, "Program.cs"),
    'var builder = WebApplication.CreateBuilder(args);\nvar app = builder.Build();\napp.UseDefaultFiles();\napp.UseStaticFiles();\napp.Run();\n',
  );
  await fs.writeFile(
    path.join(stagingDirectory, "RebuiltWebsite.csproj"),
    '<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup></Project>',
  );
  await fs.writeFile(
    path.join(stagingDirectory, "README.md"),
    `# ${projectName}\n\nBasic ASP.NET Core static-site scaffold. Run \`dotnet run\`.\n`,
  );
}

module.exports = {
  generateLaravel,
  generateWordPress,
  generateReact,
  generateVue,
  generateAspNet,
};
